### ISSUE TITLE
可以实现字符组吗？

### ISSUE THREAD

**Issue by huyaocode** [sunhengzhe/regex-engine#4]

**Comment by huyaocode** [comment]
`[a-z]`    `[0-9]`  `[abc]` 这种

**Comment by sunhengzhe** [comment]
@huyaocode 写这个项目是当时看了一些关于正则表达式的文章和书，目前暂时不打算继续开发了哦，实现的思路我记在 [这篇文章](https://segmentfault.com/a/1190000018258326) 里了，另外主要参考了 [这篇文章](https://deniskyashif.com/2019/02/17/implementing-a-regular-expression-engine/)。如果你感兴趣，完全可以在这个代码上继续开发~
